### ISSUE TITLE
Unclear explanation of difficulty retargeting 

### ISSUE THREAD

**Issue by pdaian** [bitcoinbook/bitcoinbook#206]
I find the explanation of difficulty re targeting unclear / unsatisfactory / perhaps even wrong?

As I Tweeted at https://twitter.com/phildaian/status/796881904406589440:

"In simple terms: If the network is finding blocks faster than every 10 minutes, the difficulty increases. If block discovery is slower than expected, the difficulty decreases." should be changed to more clearly explain difference between difficulty and target.  It is inconsistent with the equation on the next line:
 
New Difficulty = Old Difficulty * (Actual Time of Last 2016 Blocks / 20160 minutes)
 
Allegedly, "If block discovery is slower than expected, the difficulty decreases."  Let's say block discovery is twice as slow as expected, and take 40320 mins.  New Difficulty = Old Difficulty * (40320 minutes / 20160 minutes) = Old Difficulty * 2, which is clearly an increase, not a decrease.
 
The relationship between difficulty and target should be explained more clearly.  The equation should be for the calculation of the target, not the difficulty, or the phrasing of the text should be changed.
 
New Target = Old Target * (Actual Time of Last 2016 Blocks / 20160 minutes)
(and 1 sentence explaining the relationship between difficulty and target, perhaps)
"In simple terms: If the network is finding blocks faster than every 10 minutes, the difficulty increases, decreasing the target. If block discovery is slower than expected, the difficulty decreases, increasing the target."
 
In its current form, the text makes the target/difficulty relationship and block mechanics more confusing, not less :).

Top answer of http://bitcoin.stackexchange.com/questions/8806/what-is-difficulty-and-how-it-relates-to-target should also be included more clearly.

**Comment by wbnns** [comment]
@pdaian Hello, thanks for taking the time to bring this up and expound on what can be improved. We'll keep this open, as @aantonop mentioned on Twitter, so it can be revised in the second edition.

**Comment by aantonop** [comment]
@pdaian I made significant modifications throughout. Clarified difference between difficulty and target, re-wrote most of using the terms the "target", "proof-of-work target" and "retarget". Explained the inverse relationship between target and difficulty, fixed the equation to make it reference target (not difficulty). 

Your feedback was very helpful and I think I addressed this issue. 

Please review the revised [Chapter 10](https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch10.asciidoc) and let me know if I addressed the issue adequately. 

Unless it needs additional work, I will close this issue...

**Comment by babelpainterwell** [comment]
It seems to me the issue still persist.

In current version of the book, "New Target = Old Target * (20160 minutes / Actual Time of Last 2015 Blocks)" is still suggesting when the discovery is slower than expected, the target will decrease, which actually leads to a rise in difficulty. Instead, we want to make the process easier while facing slow discovery, meaning decreasing difficulty/ raising target should be ideal.
